2025-09-19 05:48:56,692 - INFO - Loading data...
2025-09-19 05:48:56,696 - INFO - Data loaded successfully
2025-09-19 05:48:56,698 - INFO - Running pipeline ...
2025-09-19 05:48:56,703 - ERROR - Pipeline failed: name 'clean_transform_price' is not defined
Traceback (most recent call last):
  File "C:\Users\Adham\AppData\Local\Temp\ipykernel_16212\4138661591.py", line 51, in pipeline
    clean_transform_price(price_re),
    ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'clean_transform_price' is not defined. Did you mean: 'clean_transform_postcode'?
